### ISSUE TITLE
Can you help/suggest me how quickly I can replace external applications such as PowerRun so that my script can access GetTrustedInstaller after running?

### ISSUE THREAD

**Issue by RemixPL1994** [ionuttbara/windows-defender-remover#105]
@ionuttbara 

Hello. I privately write scripts in .bat / .cmd for myself and convert them to .exe so that I can use them with administrator privileges, etc.

I have some scripts where they require PowerRun/GetTrustedInstaller.

Can you help/suggest me how quickly I can replace external applications such as PowerRun so that my script can access GetTrustedInstaller after running?

E.g. I would like to delete windows files and corrupt them to emergency remove my operating system.

Without access to GetTrustedInstaller, I get a command error and denial on many files (because they are protected).

Let me know if I can write you a PM or email.

Or ask me for my email and write to me yourself - if I can ask you to do so.

I don't share any of my scripts publicly so I won't harm anyone - if you're concerned about that.

**Comment by ionuttbara** [comment]
thanks for message. you are free to write into mail because i respond quickly.
you can use RunAsTi a @AveYo <a href="https://github.com/AveYo/LeanAndMean">project</a> it runs as TrustedInstaller privilige.
Also if you want to go something extreme you can do that with IoBit Unlocker, but that is hard to integrate into scripts. But its not working with Windows insider build 25905 or newer due enforced Rust-written Kernel. A example to deploy into script is:
```
IoBitUnlocker.exe /delete "C:\Windows\System32","C:\Windows\explorer.exe","path of files and folders"
```
Note using IoBit Unlocker it will get a message Operation Succeed, so i don't know how to do silently, better use RunAsTi because it integrates easy into script.

**Comment by ionuttbara** [comment]
my discord id is ionuttbara .

**Comment by ionuttbara** [comment]
check your discord.
