### ISSUE TITLE
Microsoft Store fvcked up

### ISSUE THREAD

**Issue by bufce2010** [ionuttbara/windows-defender-remover#111]
As the title says, this app fvcked up the whole app store and I had to reinstall the windows.
please add a "safe" option to the app or add a warning that the windows store will stop functioning.

**Comment by ionuttbara** [comment]
this was added since version 12.5.2, also every version it includes the warning.
Also in the principal window, it says what happens if you press the button , etc.

**Comment by alfablac** [comment]
Gonna have to agree it's very unsafe to run this script. 
Along with a lot of breaking (the MS Store becomes useless, and you can't even uninstall apps that were previously installed from there)
It also stops Edge from downloading files from some sources because of 'virus scan failed'
The worse part is that using R to 'undo' what was done does nothing actually.
Currently looking for a better way to reinstate things without having to resort on a full Windows reinstall.

**Comment by bufce2010** [comment]
> this was added since version 12.5.2, also every version it includes the warning. Also in the principal window, it says what happens if you press the button , etc.

No there is no warning, I've just downloaded it and tested it on another PC.
if you mean that 5 seconds count-down then it's not clear and needs The Flash to catch it xD

**Comment by bufce2010** [comment]
> Gonna have to agree it's very unsafe to run this script. Along with a lot of breaking (the MS Store becomes useless, and you can't even uninstall apps that were previously installed from there, also running the .msix bundles won't work if the app was already installed - still looking for a way to make the OS understand it's not installed) It also stops Edge from downloading files from some sources because of 'virus scan failed' The worse part is that using R to 'undo' what was done does nothing actually. Currently looking for a better way to reinstate things without having to resort on a full Windows reinstall.
> 
> EDIT: Also for anyone looking for safe options, download sysinternals Autoruns, enter safe mode, and use the app to disable the services related to Microsoft defender as well the defender manager MsMpEng. I have to reinforce that the script on this repo is very intrusive

Good luck, please let me know if you found a way, I've reinstalled a new windows after 3 days of searching :(

**Comment by alfablac** [comment]
> Good luck, please let me know if you found a way, I've reinstalled a new windows after 3 days of searching :(

Yeah, I couldn't find it, I'm not that strong to keep up for 3 days lol 

Easiest (and shortest) path I could find for now is running the in place upgrade, asking it to keep your files from the current installation
https://www.microsoft.com/software-download/windows11
And reregistering the UWP apps that got fucked up 
Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

I recommend disabling the services on Autoruns instead of some of the messy stuff the repo script does like disabling UAC and removing some .dlls. https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns

**Comment by bufce2010** [comment]
> > Good luck, please let me know if you found a way, I've reinstalled a new windows after 3 days of searching :(
> 
> Yeah, I couldn't find it, I'm not that strong to keep up for 3 days lol
> 
> Easiest (and shortest) path I could find for now is running the in place upgrade, asking it to keep your files from the current installation https://www.microsoft.com/software-download/windows11 And reregistering the UWP apps that got fucked up on PowerShell `Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`
> 
> I recommend disabling the Windows Defender related services on Autoruns instead of some of the messy stuff the repo script does like disabling UAC and removing some .dlls. https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns

Made a reset but drivers didn't work even Mouse&keyboard, so I had to fresh install, and thankfully was able to setup company's apps (it's a pc at work lol) and have access to cameras so disabled them till finished 😁
Another method to disable Windows Defender is to notice and write down it's services' exe files location  then boot to safe mode and rename all of them by adding 000 to the names, do that for folders as well.
Also you can boot from a WinPE like Sergi Strelec or hiren' without burning the ISO to usb flash disk or DVD.

**Comment by ionuttbara** [comment]
take ownership doesnt help much, i tried in Defender Remover 7.0 (launched since 2020/2021) but sometimes fails, so that's why i move to that.
Autoruns and 7-Zip are good apps to remove Defender's resources. (Autoruns for services and 7-Zip for files if that applications are running as administrator.)

**Comment by bufce2010** [comment]
> take ownership doesnt help much, i tried in Defender Remover 7.0 (launched since 2020/2021) but sometimes fails, so that's why i move to that. Autoruns and 7-Zip are good apps to remove Defender's resources. (Autoruns for services and 7-Zip for files if that applications are running as administrator.)

takeown helps only to rename files inside syswow64 & system32 folders, will try autoruns next time I need to disable Windows defender

**Comment by alfablac** [comment]
> Another method to disable Windows Defender is to notice and write down it's services' exe files location then boot to safe mode and rename all of them by adding 000 to the names, do that for folders as well.

Yep, it's what Autoruns changes on safe mode, not renaming I mean, but stopping the Defender related services. It's the simplest way with minimal mess, and funnily enough I also did that on my company PC which I was able to take ownership lol
Not sure how your company works, but on mine everything is usually reset with a policy update when connected to the VPN... I fixed that by installing a VM so I never run the VPN locally heh
