### ISSUE TITLE
0x80073CF9 - Microsoft Store apps

### ISSUE THREAD

**Issue by Yberion** [ionuttbara/windows-defender-remover#125]
## *What* affects the bug ?
`Microsoft Store`.

## *When* does this occur?
When trying to update `Notepad` through `Windows Store` for example.

## *In which* version of Windows does this issue happen ? Write version complete.
```
Windows 11 Pro
23H2
Installed the 25/‎12/‎2023
22631.2861
```

## *How* do we replicate the issue?
- I installed Windows 11 Pro
- I executed this tool https://github.com/LeDragoX/Win-Debloat-Tools
- Restart computer
- Then executed `windows-defender-remover` on version `12.6.3` (if I remember correctly)
  - `Press (Y) for removing Defender and Security Components (old method, breaking Windows Updates/UWP in some version of Windows, removes files and unregisters classes)`
- Then restarted
- Because it happened that the Malware service was still there, I executed 
[Disable_Windows_Defender_Win11.txt](https://github.com/ionuttbara/windows-defender-remover/files/13834793/Disable_Windows_Defender_Win11.txt) (I renamed to `.txt`)
- Restarted

## Expected behavior (if you have any solution write here.)
No error.

## Other Comments

I was able to reinstall Notepad with `Add an Optional feature` directly on Windows, but won't be the case for all apps.

**Comment by BreadnPlay** [comment]
Have you been able to find a fix?

**Comment by BreadnPlay** [comment]
I think I did a dumb mistake of downloading this and removing the defender completely as I have had the same mistake as you here. I ended up getting a windows update that led to my taskbar disappearing with literally no fix at all. 

I have tried countless times to fix it today almost the whole day but sadly there was not other solution than resetting my laptop and now i have realized that so many problems i have been having like windows explorer crashing randomly and stuff like that was from this remover. I hope that if anyone is going to use this they do not remove the whole thing and perhaps only disable it. I have disabled it by putting a command in the registry, simple but effective. 

I also hope that Ionut can just put it in the front page that this is a very common windows destruction bug because this Github was the first thing on my search for "windows defender remover"

**Comment by ylmw0131** [comment]
I got errors after ran this program on my latest Windows 11 Pro, my notepad and Microsoft Store are not able to launch after running the remover .bat which lead me needed to wholly reinstall my Windows 11 Pro today.

**Comment by ionuttbara** [comment]
if the app is Xbox Indetify Provider its from EOL section of AppxProvisioned Package in lastest Windows Update. If not, let me know.

**Comment by ybph** [comment]
I got this issue too,I don't want to reinstall OS OMG

**Comment by fanti1** [comment]
My windows 11 is with the taskbar crashing too, I cant use the search or even click at the date, anything works anymore...

**Comment by yolaws** [comment]
> I got errors after ran this program on my latest Windows 11 Pro, my notepad and Microsoft Store are not able to launch after running the remover .bat which lead me needed to wholly reinstall my Windows 11 Pro today.


I'm using Windows 11 Insider Preview 10.0.26080.1100.

After running Windows Defender Remover (v12.7.2), the Windows Store was no longer able to start, and according to the Windows log this problem would be related to the "AppXAllUserStore.dll" file.

Fortunately I solved this problem using the commands below, I can't say that the 3 commands are necessary for this, because I forgot to try to initialize the Windows Store after using each command.

Maybe these commands can be useful to you.

Try running each one of them and after running each command line try running Windows Store.

- - -

➜ Press Windows Key + R Key ➜ Run ➜ **wsreset.exe**
➜ Try to open the Windows Store

➜ PowerShell (AS ADMIN) ➜ **$manifest = (Get-AppxPackage Microsoft.WindowsStore).InstallLocation + '\AppxManifest.xml' ; Add-AppxPackage -DisableDevelopmentMode -Register $manifest**
➜ Try to open the Windows Store

➜ PowerShell (AS ADMIN) ➜ **Get-AppxPackage | ForEach-Object { Add-AppxPackage -DisableDevelopmentMode -Register ($_.InstallLocation + '\AppxManifest.xml')}**
➜ Try o open the Windows Store
