### ISSUE TITLE
DOES NOT REMOVE WINDOWS DEFENDER AND JUST BREAKS WINDOWS

### ISSUE THREAD

**Issue by Sequential-circuits** [ionuttbara/windows-defender-remover#191]
Running windows 11 and tried this software. It only removed all access to the windows defender settings and removed the pin login so I had to reset windows

**Comment by ionuttbara** [comment]
what error you get? this text does not have sense.

**Comment by mormaus301** [comment]
> what error you get? this text does not have sense.
Probably, author meant that the script somehow negatively affected the ability to enter windows using a pin-login (if it was set during installation). I had this once, when I set a pin-code during installation, and after using the script and reboot the pc, it began to ask me for some password which I never set, and I had to reinstall the windows.

**Comment by MNLierman** [comment]
> what error you get? this text does not have sense.

What error? My text doesn't make sense? Have you tried this tool/script on latest Win 11 builds? I don't think you have. It clearly doesn't work. Not only does it not work but it breaks very core fundamental Services of Windows 11.

 Specifically it breaks windows store, firewall, and many other services, and it doesn't actually remove defender. Msmpeng is still running. Go ahead try it, it doesn't work. I have found since then some exploits that do work, but most are not going to work. 

 From 24H2 onwards. Microsoft closed most of the exploits used by these scripts and tools to try to disable defender. Even when you disabled defender through group policy, msnpng is still running in the background, consuming resources, consuming ram, scanning items, there's no way to turn it off without using a proper exploit or using safe mode. 

Yes, using safe mode is probably the easiest for anyone to use, no third-party tools or scripts required. Use Ms config under selective startup, select safe mode, boot in a safe mode, use reg edit and delete the services for defender, name wdboot, wdfilt, and windefend, go to Program Files and rename the files Core Service and Msmpeng.exe to .exe.cold – .cold so that it won't be deleted by a file cleanup tool later on. In case you need to re enable Defender. 

So unless this tool/script has been updated since my comment, then go ahead and try, it doesn't work. Safe mode does, there's a couple of other exploits out there that work as well, but I'm not going to point them out because Microsoft has a tendency to quickly find those and get rid of them. Use Safe Mode and avoid tools like this which breaks Windows store and Firewall.
