### ISSUE TITLE
how to enable defender again?

### ISSUE THREAD

**Issue by emilmuhi6** [ionuttbara/windows-defender-remover#194]
i removed windows defender in windows 11 but i want to get it back again without reseting my pc what do i have to do to get it back again ? please help

**Comment by MNLierman** [comment]
I don't think you can. There isn't a restore option. I'm watching the issues trying to find someone who has successfully done what you are asking. I really can't reinstall Windows but it looks like I may have to. You can try an In-place Upgrade like I did. Go to uupdump, download that and run it, it will run a script that downloads a bunch of files, and what you end up with is a Windows 11 ISO that will match or exceed your version of Windows 11 which is what you want for this. When you do an in-place upgrade and it matches or exceeds your version of Windows, the registry is migrated and you end up with sort of a clean install of Windows without resetting.

If that is too complicated for you, you could Google Windows 11 ISO and download it directly from Microsoft and if you haven't taken any recent big upgrades then it should meet or exceed your version and migrate your registry, thus re-enabling and fixing Defender.

Unfortunately, and I found this out the hard way like everyone else, it is NOT possible to disable Defender in WIndows 11 anymore without corrupting Updates, Windows Store, and the Windows Firewall. Things are too intertwined, and Microsoft engineers did NOT do this on purpose. It just happens. Windows is 30 years old and they are working fast in developement, they have 10 different teams that merge code for each release. It gets messy when you're this large of a company and 80% of the world uses your OS. So I don't blame them, it is what it is. 

If you have System Restore turned on and you disabled Defender within the last 30 days, you could potentially use that too.

**Comment by dasTohsy** [comment]
https://github.com/ionuttbara/windows-defender-remover/issues/199

i hope, this helps

**Comment by MNLierman** [comment]
I discovered the only way to reverse the damage caused by programs like
this, was to download the latest Windows 11 ISO from UUP Dump (careful to
select your build and release track - it must match) and then performing an
in-place upgrade. The in place upgrade is done by extracting the ISO that
you get to the root of the C drive, and then executing setup that exe and
selecting keep all data and programs. The computer will reboot several
times, and when it comes back, hopefully everything is restored just as it
should have been on a clean install. This is what I've done and this is
what works.

**Comment by ionuttbara** [comment]
You can't.
Windows Update is working , its not broke. If the update package includes updates for Windows Defender Definition, Windows Update will not show as update (it knows the antivirus is not there, since 12.6.8), but normal security cumulative updates are working. also, its a catch. If the update includes the Security Center , Defender Sys files or the windows secHealthUi Update you'll get an error about not found. in Windows 11 24H2 works fine.
